USE TaskDB;


CREATE TABLE Tasks (
    id INT PRIMARY KEY IDENTITY (1,1),
    title NVARCHAR(255) NOT NULL,
    description NVARCHAR(MAX),
    status NVARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT GETDATE()
);